# -*- coding: utf-8 -*-
"""detectobjects.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TOYOTRmihTQ1YrumC9E2rqmwJmt1e1JP
"""

import os
import glob
import cv2
import numpy as np

# 1. Define your input and output directories
INPUT_FOLDER = '/content/dataset'
OUTPUT_FOLDER = '/content/data_set'

os.makedirs(OUTPUT_FOLDER, exist_ok=True)

# Get all images from the input folder
image_extensions = ('*.png')
image_paths = []
for ext in image_extensions:
    image_paths.extend(glob.glob(os.path.join(INPUT_FOLDER, ext)))

print(f"Found {len(image_paths)} images to process.\n" + "="*40)

# Define brown color range for detection
lower_brown = np.array([10, 40, 40])
upper_brown = np.array([30, 255, 255])

# Define kernel for morphological operations for edge cleaning
kernel_morph_edges = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3)) # Smaller kernel for edge cleaning

# 2. Process each image
for img_path in image_paths:
    # Ensure we are processing a file, not a directory like '.'
    if not os.path.isfile(img_path):
        print(f"Skipping {img_path}: Not a valid file.")
        continue

    filename = os.path.basename(img_path)
    image = cv2.imread(img_path)

    if image is None:
        print(f"Skipping {filename}: Unable to read file.")
        continue

    # Get image dimensions
    img_h, img_w = image.shape[:2]
    max_area = img_h * img_w

    # Step A: Convert to HSV and create a brown mask
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    brown_mask = cv2.inRange(hsv, lower_brown, upper_brown)

    # Step B: Apply Canny edge detection on the brown mask to get clearer boundaries
    # Using appropriate thresholds for a binary mask (0-255)
    edges = cv2.Canny(brown_mask, 50, 150) # Canny thresholds can be fine-tuned

    # Step C: Clean up the edges using morphological closing to connect broken lines
    # This helps in forming coherent contours for the box
    cleaned_edges = cv2.morphologyEx(edges, cv2.MORPH_CLOSE, kernel_morph_edges)

    # Step D: Find contours in the cleaned edges
    # Use RETR_EXTERNAL to find only the outermost contours
    contours, _ = cv2.findContours(cleaned_edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    box_contour = None
    # Sort contours by area, largest first, to prioritize the main box
    sorted_contours = sorted(contours, key=cv2.contourArea, reverse=True)

    for cnt in sorted_contours:
        area = cv2.contourArea(cnt)

        # Guard rail: Ignore contours that are too small or too large
        # Adjust these ratios as needed based on expected box size relative to image
        if area > (max_area * 0.98) or area < (max_area * 0.01): # Adjusted min area threshold slightly
            continue

        # Approximate the contour to a polygon and check if it's roughly rectangular
        epsilon = 0.02 * cv2.arcLength(cnt, True)
        approx = cv2.approxPolyDP(cnt, epsilon, True)

        # If the contour has 4 vertices, it's likely a rectangle (or close to it)
        # This helps to select the actual box over other random brown spots
        if len(approx) == 4:
            box_contour = cnt
            break
        # If no 4-vertex contour is found, fallback to the largest valid contour
        elif box_contour is None: # Only assign if box_contour is still None
            box_contour = cnt
            break # Consider only the largest valid contour as box_contour

    # Step E: Crop and Save
    if box_contour is not None:
        x, y, w, h = cv2.boundingRect(box_contour)

        # Add a tiny 5-pixel padding buffer so we don't slice the box too tightly
        pad = 5
        x_start = max(0, x - pad)
        y_start = max(0, y - pad)
        x_end = min(img_w, x + w + pad)
        y_end = min(img_h, y + h + pad)

        cropped_image = image[y_start:y_end, x_start:x_end]

        output_path = os.path.join(OUTPUT_FOLDER, filename)
        cv2.imwrite(output_path, cropped_image)
        print(f"Successfully cropped: {filename}")
    else:
        print(f" Failed to detect box boundaries in: {filename}")

print("="*40 + "\n Batch processing finished! Double-check your 'data_set' folder.")

import cv2
import numpy as np
import os
import glob
from google.colab.patches import cv2_imshow

def process_and_classify_objects(image_path):
    # 1. Read the image
    img = cv2.imread(image_path)
    if img is None:
        print(f"Could not read image: {image_path}")
        return

    # 2. Normalize size (Resizing to a fixed standard 800x800 for consistent computing)
    img = cv2.resize(img, (800, 800))
    output_img = img.copy()

    # 3. Remove blur without affecting edges (Bilateral Filter)
    # d=9, sigmaColor=75, sigmaSpace=75 are standard optimized values
    filtered = cv2.bilateralFilter(img, 9, 75, 75)

    # 4. Convert to Grayscale and apply Canny Edge Detection
    gray = cv2.cvtColor(filtered, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 40, 120)

    # 5. Morphological closing to connect fragmented edges of the objects
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (7, 7))
    closed = cv2.morphologyEx(edges, cv2.MORPH_CLOSE, kernel, iterations=3)

    # 6. Find Contours
    contours, _ = cv2.findContours(closed, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    for c in contours:
        area = cv2.contourArea(c)

        # Filter out very small noise and the massive brown box itself
        if area < 8000 or area > 400000:
            continue

        # 7. Determine Shape (Square vs Circle)
        peri = cv2.arcLength(c, True)
        approx = cv2.approxPolyDP(c, 0.04 * peri, True)

        # A square usually has 4 corners. Allow 4-5 to account for slightly rounded edges
        is_square = len(approx) >= 4 and len(approx) <= 5

        # Circularity check as a fallback (4 * pi * area / perimeter^2)
        circularity = 4 * np.pi * (area / (peri * peri))
        if circularity > 0.8:
            is_square = False # High circularity means it's a circle

        # 8. Extract Region of Interest (ROI) for Color Classification
        x, y, w, h = cv2.boundingRect(c)
        roi = filtered[y:y+h, x:x+w]

        # Convert ROI to HSV for robust color detection under varying lighting
        hsv_roi = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)

        # Define HSV color boundaries for the patterns
        lower_green = np.array([35, 40, 40])
        upper_green = np.array([85, 255, 255])

        lower_purple = np.array([115, 30, 40])
        upper_purple = np.array([160, 255, 255])

        lower_black = np.array([0, 0, 0])
        upper_black = np.array([179, 255, 70]) # Low Value (V) indicates black

        # Create color masks
        green_mask = cv2.inRange(hsv_roi, lower_green, upper_green)
        purple_mask = cv2.inRange(hsv_roi, lower_purple, upper_purple)
        black_mask = cv2.inRange(hsv_roi, lower_black, upper_black)

        total_pixels = roi.shape[0] * roi.shape[1]

        # Calculate percentage of specific colors in the object
        green_ratio = cv2.countNonZero(green_mask) / total_pixels
        purple_ratio = cv2.countNonZero(purple_mask) / total_pixels
        black_ratio = cv2.countNonZero(black_mask) / total_pixels

        # 9. Classify based on Shape + Color Pattern Ratios
        label = "Unknown"
        color = (0, 255, 255) # Default yellow text

        if is_square:
            if black_ratio > 0.4:
                label = "Obj 1: Black Square"
                color = (0, 0, 0)
            elif green_ratio > 0.02: # Even 2% green pixels means it's the green pattern
                label = "Obj 2: White & Green Square"
                color = (0, 200, 0)
            elif purple_ratio > 0.02: # Even 2% purple pixels means it's the purple pattern
                label = "Obj 3: Purple & White Square"
                color = (200, 0, 200)
            else:
                label = "Square (Unclassified)"
        else: # It is circular
            if black_ratio > 0.4:
                label = "Obj 4: Black Circular"
                color = (0, 0, 0)
            else:
                # If it's a circle and not black, it must be the white one
                label = "Obj 5: White Circular"
                color = (255, 255, 255)

        # 10. Draw Results on Image
        cv2.drawContours(output_img, [c], -1, (0, 255, 0), 3) # Draw green contour

        # Put text background for better visibility
        (text_w, text_h), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.7, 2)
        cv2.rectangle(output_img, (x, y - text_h - 10), (x + text_w, y), (200, 200, 200), -1)

        # Put Text
        cv2.putText(output_img, label, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.7, color, 2)

    # Display Output in Colab
    print(f"--- Results for {os.path.basename(image_path)} ---")
    cv2_imshow(output_img)
    print("\n")

# --- Execution Block ---
# 1. Define your specific dataset path
dataset_path = '/content/dataset/'

# 2. Search for images ONLY inside that specific folder
image_files = glob.glob(os.path.join(dataset_path, '*.png'))

# 3. Execution logic
if len(image_files) == 0:
    print(f"No images found in {dataset_path}. Please check your folder structure.")
else:
    print(f"Found {len(image_files)} images. Starting processing...\n")
    for img_file in image_files:
        process_and_classify_objects(img_file)

import cv2
import numpy as np
import os
import glob
from google.colab.patches import cv2_imshow

def process_and_classify_objects(image_path):
    # 1. Read the image
    original_img = cv2.imread(image_path)
    if original_img is None:
        print(f"Could not read image: {image_path}")
        return

    # 2. Normalize size (800x800)
    img = cv2.resize(original_img, (800, 800))
    output_img = img.copy()

    # 3. Aggressively remove blur (Unsharp Masking) to crisp up the edges
    gaussian_blur = cv2.GaussianBlur(img, (0, 0), 3.0)
    sharpened = cv2.addWeighted(img, 1.5, gaussian_blur, -0.5, 0)

    # 4. Light Bilateral Filter to remove noise but keep the newly sharpened edges
    filtered = cv2.bilateralFilter(sharpened, 5, 50, 50)

    # 5. Grayscale & Canny Edge Detection (Lowered thresholds to catch fine gaps)
    gray = cv2.cvtColor(filtered, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 30, 100)

    # 6. Dilation - Much smaller kernel (3x3) to connect lines without merging boxes!
    kernel = np.ones((3, 3), np.uint8)
    closed = cv2.dilate(edges, kernel, iterations=1)

    # 7. Find Contours
    contours, _ = cv2.findContours(closed, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    for c in contours:
        area = cv2.contourArea(c)

        # Strict area filtering (Ignoring dust and the brown box)
        if area < 12000 or area > 350000:
            continue

        # Get Aspect Ratio to filter out weird merged blobs (Squares/Circles have a ~1:1 ratio)
        x, y, w, h = cv2.boundingRect(c)
        aspect_ratio = float(w) / h
        if aspect_ratio < 0.7 or aspect_ratio > 1.3:
            continue

        # 8. Determine Shape (Square vs Circle)
        peri = cv2.arcLength(c, True)
        approx = cv2.approxPolyDP(c, 0.04 * peri, True)

        # 4 to 6 corners account for the slightly rounded box corners
        is_square = 4 <= len(approx) <= 6

        # Circularity fallback formula
        circularity = 4 * np.pi * (area / (peri * peri))
        if circularity > 0.82:
            is_square = False

        # 9. Extract STRICT Region of Interest using a Mask (No background leakage)
        mask = np.zeros(gray.shape, dtype=np.uint8)
        cv2.drawContours(mask, [c], -1, 255, -1)

        # Crop down to just the bounding rect for faster processing
        obj_cropped = filtered[y:y+h, x:x+w]
        mask_cropped = mask[y:y+h, x:x+w]

        hsv_roi = cv2.cvtColor(obj_cropped, cv2.COLOR_BGR2HSV)

        # Better tuned HSV boundaries
        lower_green = np.array([35, 30, 40])
        upper_green = np.array([90, 255, 255])

        lower_purple = np.array([110, 20, 40])
        upper_purple = np.array([165, 255, 255])

        lower_black = np.array([0, 0, 0])
        upper_black = np.array([180, 255, 65]) # Strict cut-off for pitch black

        # Create color masks
        green_mask = cv2.inRange(hsv_roi, lower_green, upper_green)
        purple_mask = cv2.inRange(hsv_roi, lower_purple, upper_purple)
        black_mask = cv2.inRange(hsv_roi, lower_black, upper_black)

        # Only count pixels that are strictly inside the contour shape
        valid_pixels = cv2.countNonZero(mask_cropped)
        if valid_pixels == 0: continue

        green_ratio = cv2.countNonZero(cv2.bitwise_and(green_mask, mask_cropped)) / valid_pixels
        purple_ratio = cv2.countNonZero(cv2.bitwise_and(purple_mask, mask_cropped)) / valid_pixels
        black_ratio = cv2.countNonZero(cv2.bitwise_and(black_mask, mask_cropped)) / valid_pixels

        # 10. Classification Engine
        label = "Unknown"
        color = (0, 255, 255) # Yellow default

        if is_square:
            if black_ratio > 0.5:
                label = "Obj 1: Black Square"
                color = (0, 0, 0)
            elif green_ratio > 0.015: # 1.5% green pattern is enough to trigger
                label = "Obj 2: Wht/Grn Square"
                color = (0, 200, 0)
            elif purple_ratio > 0.015:
                label = "Obj 3: Purp/Wht Square"
                color = (200, 0, 200)
            else:
                label = "Unclassified Square"
        else: # Circular
            if black_ratio > 0.5:
                label = "Obj 4: Black Circular"
                color = (0, 0, 0)
            else:
                label = "Obj 5: White Circular"
                color = (255, 255, 255)

        # 11. Draw Results
        cv2.drawContours(output_img, [c], -1, (0, 255, 0), 3)

        # Text Background
        (text_w, text_h), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
        cv2.rectangle(output_img, (x, y - text_h - 10), (x + text_w, y), (200, 200, 200), -1)

        # Text Label
        cv2.putText(output_img, label, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

    # Output
    print(f"--- Results for {os.path.basename(image_path)} ---")
    cv2_imshow(output_img)
    print("\n")


# --- Execution Block ---
dataset_path = '/content/dataset/'

image_files = glob.glob(os.path.join(dataset_path, '*.png')) + \
              glob.glob(os.path.join(dataset_path, '*.jpg')) + \
              glob.glob(os.path.join(dataset_path, '*.jpeg'))

if len(image_files) == 0:
    print(f"No images found in {dataset_path}. Please check your folder structure.")
else:
    print(f"Found {len(image_files)} images. Starting processing...\n")
    for img_file in image_files:
        process_and_classify_objects(img_file)

import cv2
import numpy as np
import os
import glob
from google.colab.patches import cv2_imshow

def process_and_classify_objects(image_path):
    original_img = cv2.imread(image_path)
    if original_img is None:
        return

    # 1. Normalize size
    img = cv2.resize(original_img, (800, 800))
    output_img = img.copy()

    # 2. Unsharp Masking to crisp edges
    gaussian_blur = cv2.GaussianBlur(img, (0, 0), 3.0)
    sharpened = cv2.addWeighted(img, 1.5, gaussian_blur, -0.5, 0)
    filtered = cv2.bilateralFilter(sharpened, 5, 50, 50)

    # 3. Grayscale & High-Sensitivity Edge Detection (Lowered to catch black-on-brown)
    gray = cv2.cvtColor(filtered, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 20, 80)

    # 4. Morphological Closing (5x5 kernel is the "Goldilocks" zone - not too big, not too small)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
    closed = cv2.morphologyEx(edges, cv2.MORPH_CLOSE, kernel, iterations=2)

    # 5. Find Contours
    contours, _ = cv2.findContours(closed, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    for c in contours:
        area = cv2.contourArea(c)

        # Filter dust and the main brown box
        if area < 10000 or area > 350000:
            continue

        x, y, w, h = cv2.boundingRect(c)
        aspect_ratio = float(w) / h
        if aspect_ratio < 0.6 or aspect_ratio > 1.4:
            continue

        # 6. Strict Shape Math (Circularity)
        peri = cv2.arcLength(c, True)
        if peri == 0: continue

        # A square is ~0.785. A circle is ~1.0.
        # A threshold of 0.84 perfectly separates them.
        circularity = 4 * np.pi * (area / (peri * peri))
        is_circle = circularity > 0.84

        # 7. Extract STRICT Region of Interest Mask
        mask = np.zeros(gray.shape, dtype=np.uint8)
        cv2.drawContours(mask, [c], -1, 255, -1)

        obj_cropped = filtered[y:y+h, x:x+w]
        mask_cropped = mask[y:y+h, x:x+w]

        hsv_roi = cv2.cvtColor(obj_cropped, cv2.COLOR_BGR2HSV)

        # 8. Updated Color Boundaries (Accounting for glare & shadows)
        lower_green = np.array([35, 30, 40])
        upper_green = np.array([90, 255, 255])

        lower_purple = np.array([110, 20, 40])
        upper_purple = np.array([165, 255, 255])

        # Increased Value (V) to 115 to catch glare on black objects
        lower_black = np.array([0, 0, 0])
        upper_black = np.array([180, 255, 115])

        # Low Saturation indicates White/Gray
        lower_white = np.array([0, 0, 120])
        upper_white = np.array([180, 60, 255])

        # Create color masks
        green_mask = cv2.inRange(hsv_roi, lower_green, upper_green)
        purple_mask = cv2.inRange(hsv_roi, lower_purple, upper_purple)
        black_mask = cv2.inRange(hsv_roi, lower_black, upper_black)
        white_mask = cv2.inRange(hsv_roi, lower_white, upper_white)

        valid_pixels = cv2.countNonZero(mask_cropped)
        if valid_pixels == 0: continue

        # Calculate ratios
        green_ratio = cv2.countNonZero(cv2.bitwise_and(green_mask, mask_cropped)) / valid_pixels
        purple_ratio = cv2.countNonZero(cv2.bitwise_and(purple_mask, mask_cropped)) / valid_pixels
        black_ratio = cv2.countNonZero(cv2.bitwise_and(black_mask, mask_cropped)) / valid_pixels
        white_ratio = cv2.countNonZero(cv2.bitwise_and(white_mask, mask_cropped)) / valid_pixels

        # 9. Classification Engine
        label = "Unknown"
        color = (0, 255, 255) # Yellow default

        if is_circle:
            # Lowered requirement to 30% to account for heavy glare wiping out "black" pixels
            if black_ratio > 0.30:
                label = "Obj 4: Black Circular"
                color = (0, 0, 0)
            elif white_ratio > 0.30:
                label = "Obj 5: White Circular"
                color = (255, 255, 255)
            else:
                label = "Unclassified Circle"
        else: # It is a Square
            if black_ratio > 0.30:
                label = "Obj 1: Black Square"
                color = (0, 0, 0)
            elif green_ratio > 0.015: # 1.5% green pattern triggers this
                label = "Obj 2: Wht/Grn Square"
                color = (0, 200, 0)
            elif purple_ratio > 0.015: # 1.5% purple pattern triggers this
                label = "Obj 3: Purp/Wht Square"
                color = (200, 0, 200)
            else:
                label = "Unclassified Square"

        # 10. Draw Results
        cv2.drawContours(output_img, [c], -1, (0, 255, 0), 3)

        (text_w, text_h), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
        cv2.rectangle(output_img, (x, y - text_h - 10), (x + text_w, y), (200, 200, 200), -1)
        cv2.putText(output_img, label, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

    # Display in Colab
    print(f"--- Results for {os.path.basename(image_path)} ---")
    cv2_imshow(output_img)
    print("\n")

# --- Execution Block ---
dataset_path = '/content/dataset/'

image_files = glob.glob(os.path.join(dataset_path, '*.png')) + \
              glob.glob(os.path.join(dataset_path, '*.jpg')) + \
              glob.glob(os.path.join(dataset_path, '*.jpeg'))

if len(image_files) == 0:
    print(f"No images found in {dataset_path}. Please check your folder structure.")
else:
    print(f"Found {len(image_files)} images. Starting processing...\n")
    for img_file in image_files:
        process_and_classify_objects(img_file)

import cv2
import numpy as np
import os
import glob
from google.colab.patches import cv2_imshow

def process_and_classify_objects(image_path):
    original_img = cv2.imread(image_path)
    if original_img is None:
        return

    # 1. Normalize size
    img = cv2.resize(original_img, (800, 800))
    output_img = img.copy()

    # 2. Filtering
    gaussian_blur = cv2.GaussianBlur(img, (5, 5), 0)
    filtered = cv2.bilateralFilter(gaussian_blur, 5, 50, 50)

    # 3. Edge Detection
    gray = cv2.cvtColor(filtered, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 30, 90)

    # 4. Light Morphological Closing (Reduced to 3x3 to stop items from merging)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
    closed = cv2.morphologyEx(edges, cv2.MORPH_CLOSE, kernel, iterations=1)

    # 5. Use RETR_LIST instead of EXTERNAL to catch individual items inside merged boundaries
    contours, _ = cv2.findContours(closed, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)

    # Sort by area descending so we process the largest valid individual boundaries first
    contours = sorted(contours, key=cv2.contourArea, reverse=True)

    found_centers = []

    for c in contours:
        area = cv2.contourArea(c)

        # 6. Strict Area Filter to weed out merged clusters (>150k) and dust (<15k)
        if area < 15000 or area > 150000:
            continue

        x, y, w, h = cv2.boundingRect(c)
        aspect_ratio = float(w) / h
        if aspect_ratio < 0.6 or aspect_ratio > 1.4:
            continue

        # 7. Prevent duplicate contour lines around the same object
        M = cv2.moments(c)
        if M["m00"] == 0: continue
        cx = int(M["m10"] / M["m00"])
        cy = int(M["m01"] / M["m00"])

        is_duplicate = False
        for (fcx, fcy) in found_centers:
            # If a new contour's center is within 50px of an old one, ignore it
            if np.sqrt((cx - fcx)**2 + (cy - fcy)**2) < 50:
                is_duplicate = True
                break
        if is_duplicate:
            continue

        found_centers.append((cx, cy))

        # 8. Shape Math (Circularity)
        peri = cv2.arcLength(c, True)
        if peri == 0: continue

        circularity = 4 * np.pi * (area / (peri * peri))
        is_circle = circularity > 0.82

        # 9. Extract Object Mask for Color Analysis
        mask = np.zeros(gray.shape, dtype=np.uint8)
        cv2.drawContours(mask, [c], -1, 255, -1)

        obj_cropped = filtered[y:y+h, x:x+w]
        mask_cropped = mask[y:y+h, x:x+w]

        hsv_roi = cv2.cvtColor(obj_cropped, cv2.COLOR_BGR2HSV)

        # Calculate MEAN Brightness to completely bypass the glare issue
        v_channel = hsv_roi[:,:,2]
        mean_brightness = cv2.mean(v_channel, mask=mask_cropped)[0]

        # Check for specific pattern colors (Green & Purple)
        lower_green = np.array([35, 30, 40])
        upper_green = np.array([90, 255, 255])

        lower_purple = np.array([110, 20, 40])
        upper_purple = np.array([165, 255, 255])

        green_mask = cv2.inRange(hsv_roi, lower_green, upper_green)
        purple_mask = cv2.inRange(hsv_roi, lower_purple, upper_purple)

        valid_pixels = cv2.countNonZero(mask_cropped)
        if valid_pixels == 0: continue

        green_ratio = cv2.countNonZero(cv2.bitwise_and(green_mask, mask_cropped)) / valid_pixels
        purple_ratio = cv2.countNonZero(cv2.bitwise_and(purple_mask, mask_cropped)) / valid_pixels

        # 10. Classification Engine
        label = "Unknown"
        color = (0, 255, 255)

        if is_circle:
            # A low mean brightness confirms it is the black lid, regardless of glare spots
            if mean_brightness < 110:
                label = "Obj 4: Black Circular"
                color = (0, 0, 0)
            else:
                label = "Obj 5: White Circular"
                color = (255, 255, 255)
        else: # It is a Square
            if mean_brightness < 110:
                label = "Obj 1: Black Square"
                color = (0, 0, 0)
            elif green_ratio > 0.01: # 1% green pattern is enough to trigger
                label = "Obj 2: Wht/Grn Square"
                color = (0, 200, 0)
            elif purple_ratio > 0.01: # 1% purple pattern is enough to trigger
                label = "Obj 3: Purp/Wht Square"
                color = (200, 0, 200)
            else:
                label = "Unclassified Square"

        # 11. Draw Results
        cv2.drawContours(output_img, [c], -1, (0, 255, 0), 3)

        (text_w, text_h), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
        cv2.rectangle(output_img, (x, y - text_h - 10), (x + text_w, y), (200, 200, 200), -1)
        cv2.putText(output_img, label, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

    # Display in Colab
    print(f"--- Results for {os.path.basename(image_path)} ---")
    cv2_imshow(output_img)
    print("\n")

# --- Execution Block ---
dataset_path = '/content/dataset/'

image_files = glob.glob(os.path.join(dataset_path, '*.png')) + \
              glob.glob(os.path.join(dataset_path, '*.jpg')) + \
              glob.glob(os.path.join(dataset_path, '*.jpeg'))

if len(image_files) == 0:
    print(f"No images found in {dataset_path}. Please check your folder structure.")
else:
    print(f"Found {len(image_files)} images. Starting processing...\n")
    for img_file in image_files:
        process_and_classify_objects(img_file)

import cv2
import numpy as np
import os
import glob
from google.colab.patches import cv2_imshow

def process_and_classify_objects(image_path):
    original_img = cv2.imread(image_path)
    if original_img is None:
        return

    # 1. Normalize size
    img = cv2.resize(original_img, (800, 800))
    output_img = img.copy()

    # 2. Filtering
    gaussian_blur = cv2.GaussianBlur(img, (5, 5), 0)
    filtered = cv2.bilateralFilter(gaussian_blur, 5, 50, 50)

    # 3. ENHANCE CONTRAST (Crucial Fix for Black-on-Brown)
    # CLAHE forces the dark edges to become highly visible
    gray = cv2.cvtColor(filtered, cv2.COLOR_BGR2GRAY)
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
    enhanced_gray = clahe.apply(gray)

    # 4. Edge Detection with lower thresholds on the high-contrast image
    edges = cv2.Canny(enhanced_gray, 20, 60)

    # 5. Morphological Dilation & Closing (Ensures complete, unbroken shapes)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
    dilated = cv2.dilate(edges, kernel, iterations=1)
    closed = cv2.morphologyEx(dilated, cv2.MORPH_CLOSE, kernel, iterations=2)

    # 6. Find contours (Retaining RETR_LIST to find inner/touching items)
    contours, _ = cv2.findContours(closed, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
    contours = sorted(contours, key=cv2.contourArea, reverse=True)

    found_centers = []

    for c in contours:
        area = cv2.contourArea(c)

        # Widened area parameters to ensure we catch slightly smaller/larger items
        if area < 8000 or area > 200000:
            continue

        x, y, w, h = cv2.boundingRect(c)
        aspect_ratio = float(w) / h

        # Relaxed aspect ratio to account for tilted camera angles
        if aspect_ratio < 0.5 or aspect_ratio > 1.8:
            continue

        # 7. Prevent duplicate contour lines (Kept from previous working version)
        M = cv2.moments(c)
        if M["m00"] == 0: continue
        cx = int(M["m10"] / M["m00"])
        cy = int(M["m01"] / M["m00"])

        is_duplicate = False
        for (fcx, fcy) in found_centers:
            if np.sqrt((cx - fcx)**2 + (cy - fcy)**2) < 40:
                is_duplicate = True
                break
        if is_duplicate:
            continue

        found_centers.append((cx, cy))

        # 8. Shape Math (Circularity - Kept from the working White Circle logic)
        peri = cv2.arcLength(c, True)
        if peri == 0: continue

        circularity = 4 * np.pi * (area / (peri * peri))
        is_circle = circularity > 0.82

        # 9. Extract Object Mask for Color Analysis
        mask = np.zeros(gray.shape, dtype=np.uint8)
        cv2.drawContours(mask, [c], -1, 255, -1)

        obj_cropped = filtered[y:y+h, x:x+w]
        mask_cropped = mask[y:y+h, x:x+w]

        hsv_roi = cv2.cvtColor(obj_cropped, cv2.COLOR_BGR2HSV)

        # 10. Robust Color Boundaries
        lower_black = np.array([0, 0, 0])
        upper_black = np.array([180, 255, 90])  # Strict darkness cut-off

        lower_green = np.array([35, 30, 40])
        upper_green = np.array([90, 255, 255])

        lower_purple = np.array([110, 20, 40])
        upper_purple = np.array([165, 255, 255])

        black_mask = cv2.inRange(hsv_roi, lower_black, upper_black)
        green_mask = cv2.inRange(hsv_roi, lower_green, upper_green)
        purple_mask = cv2.inRange(hsv_roi, lower_purple, upper_purple)

        valid_pixels = cv2.countNonZero(mask_cropped)
        if valid_pixels == 0: continue

        black_ratio = cv2.countNonZero(cv2.bitwise_and(black_mask, mask_cropped)) / valid_pixels
        green_ratio = cv2.countNonZero(cv2.bitwise_and(green_mask, mask_cropped)) / valid_pixels
        purple_ratio = cv2.countNonZero(cv2.bitwise_and(purple_mask, mask_cropped)) / valid_pixels

        # 11. Classification Engine
        label = "Unknown"
        color = (0, 255, 255)

        if is_circle:
            # If at least 25% of the object is pure black, it's the black lid (highly glare resistant)
            if black_ratio > 0.25:
                label = "Obj 4: Black Circular"
                color = (0, 0, 0)
            else:
                label = "Obj 5: White Circular"
                color = (255, 255, 255)
        else: # It is a Square
            if black_ratio > 0.25:
                label = "Obj 1: Black Square"
                color = (0, 0, 0)
            elif green_ratio > 0.01:
                label = "Obj 2: Wht/Grn Square"
                color = (0, 200, 0)
            elif purple_ratio > 0.01:
                label = "Obj 3: Purp/Wht Square"
                color = (200, 0, 200)
            else:
                label = "Unclassified Square"

        # 12. Draw Results
        cv2.drawContours(output_img, [c], -1, (0, 255, 0), 3)

        (text_w, text_h), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
        cv2.rectangle(output_img, (x, y - text_h - 10), (x + text_w, y), (200, 200, 200), -1)
        cv2.putText(output_img, label, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

    # Display in Colab
    print(f"--- Results for {os.path.basename(image_path)} ---")
    cv2_imshow(output_img)
    print("\n")


# --- Execution Block ---
dataset_path = '/content/dataset/'

image_files = glob.glob(os.path.join(dataset_path, '*.png')) + \
              glob.glob(os.path.join(dataset_path, '*.jpg')) + \
              glob.glob(os.path.join(dataset_path, '*.jpeg'))

if len(image_files) == 0:
    print(f"No images found in {dataset_path}. Please check your folder structure.")
else:
    print(f"Found {len(image_files)} images. Starting processing...\n")
    for img_file in image_files:
        process_and_classify_objects(img_file)

import cv2
import numpy as np
import os
import glob
from google.colab.patches import cv2_imshow

def process_and_classify_objects(image_path):
    original_img = cv2.imread(image_path)
    if original_img is None:
        return

    # 1. Normalize size
    img = cv2.resize(original_img, (800, 800))
    output_img = img.copy()

    # 2. Filtering
    gaussian_blur = cv2.GaussianBlur(img, (5, 5), 0)
    filtered = cv2.bilateralFilter(gaussian_blur, 5, 50, 50)

    # 3. ENHANCE CONTRAST (CLAHE)
    gray = cv2.cvtColor(filtered, cv2.COLOR_BGR2GRAY)
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
    enhanced_gray = clahe.apply(gray)

    # 4. Edge Detection
    edges = cv2.Canny(enhanced_gray, 20, 60)

    # 5. Morphological Dilation & Closing
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
    dilated = cv2.dilate(edges, kernel, iterations=1)
    closed = cv2.morphologyEx(dilated, cv2.MORPH_CLOSE, kernel, iterations=2)

    # 6. Find contours
    contours, _ = cv2.findContours(closed, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
    contours = sorted(contours, key=cv2.contourArea, reverse=True)

    found_centers = []

    for c in contours:
        area = cv2.contourArea(c)
        if area < 8000 or area > 200000:
            continue

        x, y, w, h = cv2.boundingRect(c)
        aspect_ratio = float(w) / h
        if aspect_ratio < 0.5 or aspect_ratio > 1.8:
            continue

        M = cv2.moments(c)
        if M["m00"] == 0: continue
        cx = int(M["m10"] / M["m00"])
        cy = int(M["m01"] / M["m00"])

        is_duplicate = False
        for (fcx, fcy) in found_centers:
            if np.sqrt((cx - fcx)**2 + (cy - fcy)**2) < 40:
                is_duplicate = True
                break
        if is_duplicate:
            continue

        found_centers.append((cx, cy))

        # 7. Shape Math (Circularity)
        peri = cv2.arcLength(c, True)
        if peri == 0: continue
        circularity = 4 * np.pi * (area / (peri * peri))
        is_circle = circularity > 0.82

        # 8. Color Analysis
        mask = np.zeros(gray.shape, dtype=np.uint8)
        cv2.drawContours(mask, [c], -1, 255, -1)
        obj_cropped = filtered[y:y+h, x:x+w]
        mask_cropped = mask[y:y+h, x:x+w]
        hsv_roi = cv2.cvtColor(obj_cropped, cv2.COLOR_BGR2HSV)

        lower_black = np.array([0, 0, 0])
        upper_black = np.array([180, 255, 90])
        lower_green = np.array([35, 30, 40])
        upper_green = np.array([90, 255, 255])
        lower_purple = np.array([110, 20, 40])
        upper_purple = np.array([165, 255, 255])

        black_mask = cv2.inRange(hsv_roi, lower_black, upper_black)
        green_mask = cv2.inRange(hsv_roi, lower_green, upper_green)
        purple_mask = cv2.inRange(hsv_roi, lower_purple, upper_purple)

        valid_pixels = cv2.countNonZero(mask_cropped)
        if valid_pixels == 0: continue

        black_ratio = cv2.countNonZero(cv2.bitwise_and(black_mask, mask_cropped)) / valid_pixels
        green_ratio = cv2.countNonZero(cv2.bitwise_and(green_mask, mask_cropped)) / valid_pixels
        purple_ratio = cv2.countNonZero(cv2.bitwise_and(purple_mask, mask_cropped)) / valid_pixels

        # 9. Classification Engine
        label = "Unknown"
        color = (0, 255, 255)

        if is_circle:
            if black_ratio > 0.25:
                label = "Obj 4: Black Circular"
                color = (0, 0, 0)
            else:
                label = "Obj 5: White Circular" # FIXED: Explicit classification
                color = (255, 255, 255)
        else:
            if black_ratio > 0.25:
                label = "Obj 1: Black Square"
                color = (0, 0, 0)
            elif green_ratio > 0.01:
                label = "Obj 2: Wht/Grn Square"
                color = (0, 200, 0)
            elif purple_ratio > 0.01:
                label = "Obj 3: Purp/Wht Square"
                color = (200, 0, 200)
            else:
                label = "Unclassified Square"

        # 10. Draw Results
        cv2.drawContours(output_img, [c], -1, (0, 255, 0), 3)
        (text_w, text_h), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
        cv2.rectangle(output_img, (x, y - text_h - 10), (x + text_w, y), (200, 200, 200), -1)
        cv2.putText(output_img, label, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

    cv2_imshow(output_img)

# Execution
dataset_path = '/content/dataset/'
image_files = glob.glob(os.path.join(dataset_path, '*'))
for img_file in image_files:
    process_and_classify_objects(img_file)

import cv2
import numpy as np
import os
import glob
from google.colab.patches import cv2_imshow

def process_and_classify_objects(image_path):
    original_img = cv2.imread(image_path)
    if original_img is None: return
    img = cv2.resize(original_img, (800, 800))
    output_img = img.copy()

    # Pre-processing
    filtered = cv2.bilateralFilter(cv2.GaussianBlur(img, (5, 5), 0), 5, 50, 50)
    gray = cv2.cvtColor(filtered, cv2.COLOR_BGR2GRAY)
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
    enhanced_gray = clahe.apply(gray)
    edges = cv2.Canny(enhanced_gray, 20, 60)

    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
    closed = cv2.morphologyEx(cv2.dilate(edges, kernel, iterations=1), cv2.MORPH_CLOSE, kernel, iterations=2)
    contours, _ = cv2.findContours(closed, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)

    found_centers = []
    for c in sorted(contours, key=cv2.contourArea, reverse=True):
        area = cv2.contourArea(c)
        if area < 8000 or area > 200000: continue
        x, y, w, h = cv2.boundingRect(c)
        if (float(w) / h) < 0.5 or (float(w) / h) > 1.8: continue

        M = cv2.moments(c)
        if M["m00"] == 0: continue
        cx, cy = int(M["m10"] / M["m00"]), int(M["m01"] / M["m00"])
        if any(np.sqrt((cx - fcx)**2 + (cy - fcy)**2) < 40 for (fcx, fcy) in found_centers): continue
        found_centers.append((cx, cy))

        # Shape Logic
        peri = cv2.arcLength(c, True)
        circularity = 4 * np.pi * (area / (peri * peri)) if peri > 0 else 0
        is_circle = circularity > 0.75 # Lowered threshold to be more inclusive

        # Color Analysis
        mask = np.zeros(gray.shape, dtype=np.uint8)
        cv2.drawContours(mask, [c], -1, 255, -1)
        hsv_roi = cv2.cvtColor(filtered[y:y+h, x:x+w], cv2.COLOR_BGR2HSV)
        mask_cropped = mask[y:y+h, x:x+w]

        black_ratio = cv2.countNonZero(cv2.bitwise_and(cv2.inRange(hsv_roi, np.array([0,0,0]), np.array([180,255,90])), mask_cropped)) / cv2.countNonZero(mask_cropped)
        green_ratio = cv2.countNonZero(cv2.bitwise_and(cv2.inRange(hsv_roi, np.array([35,30,40]), np.array([90,255,255])), mask_cropped)) / cv2.countNonZero(mask_cropped)
        purple_ratio = cv2.countNonZero(cv2.bitwise_and(cv2.inRange(hsv_roi, np.array([110,20,40]), np.array([165,255,255])), mask_cropped)) / cv2.countNonZero(mask_cropped)

        # Classification
        if black_ratio > 0.25:
            label = f"Obj {'4' if is_circle else '1'}: Black {'Circular' if is_circle else 'Square'}"
            color = (0, 0, 0)
        elif is_circle:
            label = "Obj 5: White Circular"
            color = (255, 255, 255)
        elif green_ratio > 0.01:
            label = "Obj 2: Wht/Grn Square"
            color = (0, 200, 0)
        elif purple_ratio > 0.01:
            label = "Obj 3: Purp/Wht Square"
            color = (200, 0, 200)
        else:
            label = "Obj 5: White Circular"
            color = (0, 0, 255)

        cv2.drawContours(output_img, [c], -1, (0, 255, 0), 3)
        (tw, th), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
        cv2.rectangle(output_img, (x, y - th - 10), (x + tw, y), (200, 200, 200), -1)
        cv2.putText(output_img, label, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

    cv2_imshow(output_img)

for img_file in glob.glob('/content/dataset/*'): process_and_classify_objects(img_file)

import cv2
import numpy as np
import os
import glob
from google.colab.patches import cv2_imshow

def process_and_classify_objects(image_path):
    original_img = cv2.imread(image_path)
    if original_img is None: return
    img = cv2.resize(original_img, (800, 800))
    output_img = img.copy()

    # 1. Pre-processing: Blur + CLAHE (Keeps edges visible without destroying contrast)
    filtered = cv2.bilateralFilter(cv2.GaussianBlur(img, (5, 5), 0), 5, 50, 50)
    gray = cv2.cvtColor(filtered, cv2.COLOR_BGR2GRAY)
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
    enhanced_gray = clahe.apply(gray)

    # 2. Edge Detection (Standard Canny - proven to work for your layout)
    edges = cv2.Canny(enhanced_gray, 20, 60)

    # 3. Clean up the edges
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
    closed = cv2.morphologyEx(cv2.dilate(edges, kernel, iterations=1), cv2.MORPH_CLOSE, kernel, iterations=2)
    contours, _ = cv2.findContours(closed, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)

    found_centers = []

    # Sort contours by area
    for c in sorted(contours, key=cv2.contourArea, reverse=True):
        area = cv2.contourArea(c)
        if area < 8000 or area > 200000: continue

        x, y, w, h = cv2.boundingRect(c)
        if (float(w) / h) < 0.5 or (float(w) / h) > 1.8: continue

        M = cv2.moments(c)
        if M["m00"] == 0: continue
        cx, cy = int(M["m10"] / M["m00"]), int(M["m01"] / M["m00"])

        # Duplicate detection check
        if any(np.sqrt((cx - fcx)**2 + (cy - fcy)**2) < 40 for (fcx, fcy) in found_centers): continue
        found_centers.append((cx, cy))

        # Shape Analysis
        peri = cv2.arcLength(c, True)
        circularity = 4 * np.pi * (area / (peri * peri)) if peri > 0 else 0
        is_circle = circularity > 0.75

        # 4. Color Analysis (Refined Black Detection)
        hsv_roi = cv2.cvtColor(filtered[y:y+h, x:x+w], cv2.COLOR_BGR2HSV)
        mask = np.zeros(gray.shape, dtype=np.uint8)
        cv2.drawContours(mask, [c], -1, 255, -1)
        mask_cropped = mask[y:y+h, x:x+w]

        # Black detection: V channel is low (< 70), and S is low (neutral color)
        # We also check the mean value of the ROI vs the whole image to detect darkness relative to background
        v_channel = hsv_roi[:,:,2]
        mean_v = cv2.mean(v_channel, mask=mask_cropped)[0]

        # Logic: If object is significantly dark (V < 85), it is a black object
        is_black = mean_v < 85

        # 5. Classification
        if is_black:
            label = f"Obj {'4' if is_circle else '1'}: Black {'Circular' if is_circle else 'Square'}"
            color = (0, 0, 0)
        elif is_circle:
            label = "Obj 5: White Circular"
            color = (255, 255, 255)
        else:
            # Pattern check
            green_mask = cv2.inRange(hsv_roi, np.array([35, 30, 40]), np.array([90, 255, 255]))
            purple_mask = cv2.inRange(hsv_roi, np.array([110, 20, 40]), np.array([165, 255, 255]))
            green_ratio = cv2.countNonZero(cv2.bitwise_and(green_mask, mask_cropped)) / cv2.countNonZero(mask_cropped)
            purple_ratio = cv2.countNonZero(cv2.bitwise_and(purple_mask, mask_cropped)) / cv2.countNonZero(mask_cropped)

            if green_ratio > 0.01:
                label = "Obj 2: Wht/Grn Square"
                color = (0, 200, 0)
            elif purple_ratio > 0.01:
                label = "Obj 3: Purp/Wht Square"
                color = (200, 0, 200)
            else:
                label = "Unclassified"
                color = (0, 0, 255)

        cv2.drawContours(output_img, [c], -1, (0, 255, 0), 2)
        (tw, th), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 2)
        cv2.rectangle(output_img, (x, y - th - 10), (x + tw, y), (200, 200, 200), -1)
        cv2.putText(output_img, label, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

    cv2_imshow(output_img)

for img_file in glob.glob('/content/dataset/*'): process_and_classify_objects(img_file)

import cv2
import numpy as np
import os
import glob
from google.colab.patches import cv2_imshow

def process_and_classify_objects(image_path):
    original_img = cv2.imread(image_path)
    if original_img is None: return
    img = cv2.resize(original_img, (800, 800))
    output_img = img.copy()

    # 1. Pre-processing: Blur + CLAHE
    filtered = cv2.bilateralFilter(cv2.GaussianBlur(img, (5, 5), 0), 5, 50, 50)
    gray = cv2.cvtColor(filtered, cv2.COLOR_BGR2GRAY)
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
    enhanced_gray = clahe.apply(gray)

    # 2. DUAL DETECTION: Canny (edges) + Adaptive Thresholding (dark blobs)
    edges = cv2.Canny(enhanced_gray, 30, 90)
    _, adaptive = cv2.threshold(enhanced_gray, 70, 255, cv2.THRESH_BINARY_INV)
    # Combine both so faint objects are captured by thresholding and sharp ones by edges
    combined = cv2.bitwise_or(edges, adaptive)

    # 3. Clean up the combined detection
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
    closed = cv2.morphologyEx(combined, cv2.MORPH_CLOSE, kernel, iterations=2)
    contours, _ = cv2.findContours(closed, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)

    found_centers = []

    for c in sorted(contours, key=cv2.contourArea, reverse=True):
        area = cv2.contourArea(c)
        if area < 5000 or area > 200000: continue

        x, y, w, h = cv2.boundingRect(c)
        if (float(w) / h) < 0.4 or (float(w) / h) > 2.0: continue

        M = cv2.moments(c)
        if M["m00"] == 0: continue
        cx, cy = int(M["m10"] / M["m00"]), int(M["m01"] / M["m00"])

        if any(np.sqrt((cx - fcx)**2 + (cy - fcy)**2) < 40 for (fcx, fcy) in found_centers): continue
        found_centers.append((cx, cy))

        # Shape Analysis
        peri = cv2.arcLength(c, True)
        circularity = 4 * np.pi * (area / (peri * peri)) if peri > 0 else 0
        is_circle = circularity > 0.70 # Widened tolerance for black circles

        # 4. Color Analysis
        hsv_roi = cv2.cvtColor(filtered[y:y+h, x:x+w], cv2.COLOR_BGR2HSV)
        mask = np.zeros(gray.shape, dtype=np.uint8)
        cv2.drawContours(mask, [c], -1, 255, -1)
        mask_cropped = mask[y:y+h, x:x+w]

        # Check if the object is predominantly dark (Black)
        v_channel = hsv_roi[:,:,2]
        mean_v = cv2.mean(v_channel, mask=mask_cropped)[0]
        is_black = mean_v < 90

        # 5. Priority Classification Engine
        label = "Unclassified"
        color = (0, 0, 255)

        if is_black:
            label = f"Obj {'4' if is_circle else '1'}: Black {'Circular' if is_circle else 'Square'}"
            color = (0, 0, 0)
        elif is_circle:
            label = "Obj 5: White Circular"
            color = (255, 255, 255)
        else:
            green_mask = cv2.inRange(hsv_roi, np.array([35, 30, 40]), np.array([90, 255, 255]))
            purple_mask = cv2.inRange(hsv_roi, np.array([110, 20, 40]), np.array([165, 255, 255]))
            green_ratio = cv2.countNonZero(cv2.bitwise_and(green_mask, mask_cropped)) / cv2.countNonZero(mask_cropped)
            purple_ratio = cv2.countNonZero(cv2.bitwise_and(purple_mask, mask_cropped)) / cv2.countNonZero(mask_cropped)

            if green_ratio > 0.01:
                label = "Obj 2: Wht/Grn Square"
                color = (0, 200, 0)
            elif purple_ratio > 0.01:
                label = "Obj 3: Purp/Wht Square"
                color = (200, 0, 200)

        cv2.drawContours(output_img, [c], -1, (0, 255, 0), 2)
        (tw, th), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 2)
        cv2.rectangle(output_img, (x, y - th - 10), (x + tw, y), (200, 200, 200), -1)
        cv2.putText(output_img, label, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

    cv2_imshow(output_img)

for img_file in glob.glob('/content/dataset/*'): process_and_classify_objects(img_file)